CREATE TABLE storefront_settings (
    id SMALLINT PRIMARY KEY,
    hero_image_url VARCHAR(2048),
    hero_image_alt_text VARCHAR(300),
    hero_heading VARCHAR(300),
    hero_supporting_text VARCHAR(1000),
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT ck_storefront_settings_singleton CHECK (id = 1),
    CONSTRAINT ck_storefront_hero_alt CHECK (hero_image_url IS NULL OR (hero_image_alt_text IS NOT NULL AND LENGTH(TRIM(hero_image_alt_text)) > 0))
);

INSERT INTO storefront_settings (
    id, hero_image_url, hero_image_alt_text, hero_heading, hero_supporting_text, updated_at
) VALUES (
    1,
    NULL,
    NULL,
    'Handcrafted wooden goods, shaped for everyday use.',
    'Thoughtfully made pieces for calmer desks, organised homes and durable everyday rituals.',
    CURRENT_TIMESTAMP
);

CREATE TABLE navigation_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label VARCHAR(160) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT FALSE,
    display_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_navigation_groups_label CHECK (LENGTH(TRIM(label)) > 0),
    CONSTRAINT ck_navigation_groups_order CHECK (display_order >= 0)
);

CREATE INDEX idx_navigation_groups_public_order ON navigation_groups(active, display_order, id);

CREATE TABLE navigation_group_categories (
    navigation_group_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    display_order INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (navigation_group_id, category_id),
    CONSTRAINT fk_navigation_group_categories_group FOREIGN KEY (navigation_group_id) REFERENCES navigation_groups(id) ON DELETE CASCADE,
    CONSTRAINT fk_navigation_group_categories_category FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE,
    CONSTRAINT ck_navigation_group_categories_order CHECK (display_order >= 0)
);

CREATE INDEX idx_navigation_group_categories_order ON navigation_group_categories(navigation_group_id, display_order, category_id);
CREATE INDEX idx_navigation_group_categories_category ON navigation_group_categories(category_id);

CREATE TABLE navigation_group_featured_products (
    navigation_group_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    display_order INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (navigation_group_id, product_id),
    CONSTRAINT fk_navigation_group_products_group FOREIGN KEY (navigation_group_id) REFERENCES navigation_groups(id) ON DELETE CASCADE,
    CONSTRAINT fk_navigation_group_products_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
    CONSTRAINT ck_navigation_group_products_order CHECK (display_order >= 0)
);

CREATE INDEX idx_navigation_group_products_order ON navigation_group_featured_products(navigation_group_id, display_order, product_id);
CREATE INDEX idx_navigation_group_products_product ON navigation_group_featured_products(product_id);
