CREATE TABLE spring_session (
    primary_id CHAR(36) NOT NULL,
    session_id CHAR(36) NOT NULL,
    creation_time BIGINT NOT NULL,
    last_access_time BIGINT NOT NULL,
    max_inactive_interval INTEGER NOT NULL,
    expiry_time BIGINT NOT NULL,
    principal_name VARCHAR(100),
    CONSTRAINT spring_session_pk PRIMARY KEY (primary_id)
);

ALTER TABLE spring_session ADD CONSTRAINT spring_session_ix1 UNIQUE (session_id);
CREATE INDEX spring_session_ix2 ON spring_session(expiry_time);
CREATE INDEX spring_session_ix3 ON spring_session(principal_name);

CREATE TABLE spring_session_attributes (
    session_primary_id CHAR(36) NOT NULL,
    attribute_name VARCHAR(200) NOT NULL,
    attribute_bytes BYTEA NOT NULL,
    CONSTRAINT spring_session_attributes_pk PRIMARY KEY (session_primary_id, attribute_name),
    CONSTRAINT spring_session_attributes_fk FOREIGN KEY (session_primary_id)
        REFERENCES spring_session(primary_id) ON DELETE CASCADE
);

CREATE TABLE admin_login_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope_type VARCHAR(20) NOT NULL,
    scope_hash CHAR(64) NOT NULL,
    failed_at TIMESTAMP NOT NULL,
    CONSTRAINT ck_admin_login_attempt_scope CHECK (scope_type IN ('IP', 'ACCOUNT_IP'))
);

CREATE INDEX idx_admin_login_attempts_scope
    ON admin_login_attempts(scope_type, scope_hash, failed_at);
CREATE INDEX idx_admin_login_attempts_failed_at ON admin_login_attempts(failed_at);
