CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(320) NOT NULL,
    normalized_email VARCHAR(320) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    phone VARCHAR(40),
    locale VARCHAR(20) NOT NULL DEFAULT 'en',
    email_verified_at TIMESTAMP,
    account_status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uq_customers_normalized_email UNIQUE (normalized_email),
    CONSTRAINT ck_customers_account_status CHECK (account_status IN ('ACTIVE', 'DISABLED'))
);

CREATE TABLE customer_addresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    recipient_name VARCHAR(200) NOT NULL,
    company VARCHAR(200),
    street VARCHAR(200) NOT NULL,
    house_number VARCHAR(30) NOT NULL,
    address_line_2 VARCHAR(200),
    postal_code VARCHAR(30) NOT NULL,
    city VARCHAR(120) NOT NULL,
    region VARCHAR(120),
    country_code VARCHAR(2) NOT NULL,
    phone VARCHAR(40),
    default_shipping BOOLEAN NOT NULL DEFAULT FALSE,
    default_billing BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_customer_addresses_customer FOREIGN KEY (customer_id)
        REFERENCES customers(id) ON DELETE CASCADE
);

CREATE INDEX idx_customer_addresses_customer ON customer_addresses(customer_id);

CREATE TABLE customer_password_reset_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    used_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uq_customer_reset_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_customer_reset_customer FOREIGN KEY (customer_id)
        REFERENCES customers(id) ON DELETE CASCADE
);

CREATE INDEX idx_customer_reset_customer ON customer_password_reset_tokens(customer_id);
CREATE INDEX idx_customer_reset_expiry ON customer_password_reset_tokens(expires_at);

CREATE TABLE customer_auth_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action VARCHAR(30) NOT NULL,
    scope_hash CHAR(64) NOT NULL,
    attempted_at TIMESTAMP NOT NULL,
    CONSTRAINT ck_customer_auth_action CHECK (action IN ('REGISTER', 'PASSWORD_RESET_REQUEST', 'PASSWORD_RESET'))
);

CREATE INDEX idx_customer_auth_requests_scope
    ON customer_auth_requests(action, scope_hash, attempted_at);
