ALTER TABLE customers ALTER COLUMN password_hash DROP NOT NULL;

CREATE TABLE customer_social_identities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    provider VARCHAR(30) NOT NULL,
    provider_subject VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_customer_social_identity_customer FOREIGN KEY (customer_id)
        REFERENCES customers(id) ON DELETE CASCADE,
    CONSTRAINT uq_customer_social_provider_subject UNIQUE (provider, provider_subject),
    CONSTRAINT uq_customer_social_provider_customer UNIQUE (provider, customer_id),
    CONSTRAINT ck_customer_social_provider CHECK (provider IN ('google', 'apple'))
);

CREATE INDEX idx_customer_social_identity_customer
    ON customer_social_identities(customer_id);
