CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT,
    name VARCHAR(160) NOT NULL,
    slug VARCHAR(180) NOT NULL,
    description VARCHAR(1000),
    image_url VARCHAR(2048),
    sort_order INTEGER NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_categories_parent FOREIGN KEY (parent_id) REFERENCES categories(id),
    CONSTRAINT ck_categories_not_self CHECK (parent_id IS NULL OR parent_id <> id),
    CONSTRAINT uq_categories_parent_slug UNIQUE (parent_id, slug)
);

CREATE INDEX idx_categories_parent_sort ON categories(parent_id, sort_order);
CREATE INDEX idx_categories_active ON categories(active);

INSERT INTO categories (name, slug, description, sort_order, active, created_at, updated_at)
VALUES ('Uncategorized', 'uncategorized', 'Products awaiting catalog organization', 0, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

ALTER TABLE products ADD COLUMN category_id BIGINT;
ALTER TABLE products ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE products ADD COLUMN subtitle VARCHAR(300);
ALTER TABLE products ADD COLUMN featured BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE products ADD COLUMN badge VARCHAR(80);
ALTER TABLE products ADD COLUMN seo_title VARCHAR(180);
ALTER TABLE products ADD COLUMN seo_description VARCHAR(320);
UPDATE products SET category_id = (SELECT id FROM categories WHERE slug = 'uncategorized');
ALTER TABLE products ALTER COLUMN category_id SET NOT NULL;
ALTER TABLE products ADD CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories(id);
ALTER TABLE products ADD CONSTRAINT ck_products_status CHECK (status IN ('DRAFT', 'ACTIVE', 'ARCHIVED'));
CREATE INDEX idx_products_category ON products(category_id);
CREATE INDEX idx_products_category_status ON products(category_id, status);

CREATE TABLE product_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    code VARCHAR(80) NOT NULL,
    display_type VARCHAR(30) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    required BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_product_options_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
    CONSTRAINT uq_product_options_code UNIQUE (product_id, code)
);
CREATE INDEX idx_product_options_product_sort ON product_options(product_id, sort_order);

CREATE TABLE product_option_values (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    option_id BIGINT NOT NULL,
    label VARCHAR(100) NOT NULL,
    code VARCHAR(80) NOT NULL,
    swatch_hex VARCHAR(9),
    swatch_image_url VARCHAR(2048),
    sort_order INTEGER NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_option_values_option FOREIGN KEY (option_id) REFERENCES product_options(id) ON DELETE CASCADE,
    CONSTRAINT uq_option_values_code UNIQUE (option_id, code)
);
CREATE INDEX idx_option_values_option_sort ON product_option_values(option_id, sort_order);

CREATE TABLE product_variants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id VARCHAR(180) NOT NULL,
    product_id BIGINT NOT NULL,
    sku VARCHAR(120),
    combination_key VARCHAR(1000) NOT NULL,
    regular_price_cents BIGINT NOT NULL,
    sale_price_cents BIGINT,
    stock_quantity INTEGER NOT NULL DEFAULT 0,
    availability_status VARCHAR(30) NOT NULL DEFAULT 'IN_STOCK',
    active BOOLEAN NOT NULL DEFAULT TRUE,
    allow_backorder BOOLEAN NOT NULL DEFAULT FALSE,
    delivery_estimate VARCHAR(160),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_variants_product FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT uq_variants_public_id UNIQUE (public_id),
    CONSTRAINT uq_variants_combination UNIQUE (product_id, combination_key),
    CONSTRAINT ck_variants_price CHECK (regular_price_cents >= 0),
    CONSTRAINT ck_variants_sale_price CHECK (sale_price_cents IS NULL OR sale_price_cents >= 0),
    CONSTRAINT ck_variants_stock CHECK (stock_quantity >= 0)
);
CREATE INDEX idx_variants_product_active ON product_variants(product_id, active);
CREATE INDEX idx_variants_sku ON product_variants(sku);

CREATE TABLE product_variant_option_values (
    variant_id BIGINT NOT NULL,
    option_value_id BIGINT NOT NULL,
    PRIMARY KEY (variant_id, option_value_id),
    CONSTRAINT fk_variant_values_variant FOREIGN KEY (variant_id) REFERENCES product_variants(id) ON DELETE CASCADE,
    CONSTRAINT fk_variant_values_value FOREIGN KEY (option_value_id) REFERENCES product_option_values(id)
);
CREATE INDEX idx_variant_values_value ON product_variant_option_values(option_value_id);

ALTER TABLE product_images RENAME TO legacy_product_images;
CREATE TABLE product_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    image_url VARCHAR(2048) NOT NULL,
    alt_text VARCHAR(300),
    display_order INTEGER NOT NULL DEFAULT 0,
    shared BOOLEAN NOT NULL DEFAULT TRUE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_catalog_images_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
    CONSTRAINT uq_catalog_images_order UNIQUE (product_id, display_order)
);
INSERT INTO product_images (product_id, image_url, display_order, shared, active, created_at)
SELECT product_id, image_url, display_order, TRUE, TRUE, CURRENT_TIMESTAMP FROM legacy_product_images;
DROP TABLE legacy_product_images;
CREATE INDEX idx_product_images_product_active ON product_images(product_id, active, display_order);

CREATE TABLE product_variant_images (
    variant_id BIGINT NOT NULL,
    image_id BIGINT NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (variant_id, image_id),
    CONSTRAINT fk_variant_images_variant FOREIGN KEY (variant_id) REFERENCES product_variants(id) ON DELETE CASCADE,
    CONSTRAINT fk_variant_images_image FOREIGN KEY (image_id) REFERENCES product_images(id) ON DELETE CASCADE,
    CONSTRAINT uq_variant_images_order UNIQUE (variant_id, sort_order)
);

INSERT INTO product_variants (public_id, product_id, sku, combination_key, regular_price_cents, stock_quantity,
    availability_status, active, allow_backorder, created_at, updated_at)
SELECT CONCAT('default-', id), id, NULL, 'default', price_cents,
    CASE WHEN in_stock THEN 99 ELSE 0 END,
    CASE WHEN in_stock THEN 'IN_STOCK' ELSE 'OUT_OF_STOCK' END,
    active, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM products;
